// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCgj9APJ1XtdB4p6__xAQlrbnxzHtVxiY',
    appId: '1:463617522194:web:ebca96cd6a62ec8a3276cb',
    messagingSenderId: '463617522194',
    projectId: 'lista-de-compra-f7e59',
    authDomain: 'lista-de-compra-f7e59.firebaseapp.com',
    storageBucket: 'lista-de-compra-f7e59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ldEMvpW-sYFHNdFfSrByuSkHSeovk7Y',
    appId: '1:463617522194:android:e18393d789b958663276cb',
    messagingSenderId: '463617522194',
    projectId: 'lista-de-compra-f7e59',
    storageBucket: 'lista-de-compra-f7e59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwgzdl22j07DG7x9Mxys714s5JJ9rbn9o',
    appId: '1:463617522194:ios:c1e5bf90e1f35def3276cb',
    messagingSenderId: '463617522194',
    projectId: 'lista-de-compra-f7e59',
    storageBucket: 'lista-de-compra-f7e59.firebasestorage.app',
    iosBundleId: 'com.example.listaDeCompras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwgzdl22j07DG7x9Mxys714s5JJ9rbn9o',
    appId: '1:463617522194:ios:c1e5bf90e1f35def3276cb',
    messagingSenderId: '463617522194',
    projectId: 'lista-de-compra-f7e59',
    storageBucket: 'lista-de-compra-f7e59.firebasestorage.app',
    iosBundleId: 'com.example.listaDeCompras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCgj9APJ1XtdB4p6__xAQlrbnxzHtVxiY',
    appId: '1:463617522194:web:0317deb9102dc4363276cb',
    messagingSenderId: '463617522194',
    projectId: 'lista-de-compra-f7e59',
    authDomain: 'lista-de-compra-f7e59.firebaseapp.com',
    storageBucket: 'lista-de-compra-f7e59.firebasestorage.app',
  );
}
